### PR TITLE
Added support for LocalDateTime and LocalDate

### PR DESCRIPTION
**Pull request by m-lefevre**
Modified CalendarConverter.java and DateConverter.java to add support for LocalDateTime and LocalDate formats. Modified AbstractDateConverterTest.java and CalendarConverterTest.java to include coverage for added code.

### CODE REVIEW

**Comment by chhsiao90** [comment]
Hi @m-lefevre - Thanks for this PR, I'm really appreciate it. java 8 provides many convenient stuffs and I think to support it is really good. But introduce it in our core ModelMapper will cause ModelMapper only support for java 8 and above. I suggest maybe we can create a module for jdk8 stuff.

**Comment by yuranos** [comment]
@chhsiao90, what exactly do you mean by "module"? You want to put it in a separate repo? If so, it should we someone with the right to create a repo inside modelmapper account to start with.

**Comment by yuranos** [comment]
But to be honest it only makes sense if someone is actively developing new features that should be ported to several versions of the library and post java 8 projects. If there's no active development, and I don't see it, why can't we merge this PR and release a new major version?

**Comment by yuranos** [comment]
@m-lefevre , am I correct that this PR will only support LocalDate(Time) as a source, not as a destination? If so, I would expand it and add a destination support.

**Comment by chhsiao90** [comment]
Hi @yuranos - Because currently modelmapper still support Java 1.6, so we can't adds any Java 8 stuff into our core codebase. What I thought about the module, please refer how jackson do like https://github.com/FasterXML/jackson-modules-java8 or https://github.com/FasterXML/jackson-datatype-jsr310.

**Comment by chhsiao90** [comment]
hi, I'm working on this and please take a look [modelmapper-module-java8](https://github.com/chhsiao90/modelmapper-module-java8).

**Comment by chhsiao90** [comment]
Close this pull request as we still need support java6 and java7.

**Pull request closed without merging**
