### PR TITLE
Updates asm, cglib and objenesis to their latest versions

### PR DESCRIPTION
**Pull request by mdzhigarov**

### CODE REVIEW

**Comment by chhsiao90** [comment]
hi @mdzhigarov -
I got exception when I tried to package modelmapper with maven using `mvn package`.

Do you have this problem?
```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:2.4.3:shade (default) on project modelmapper: Error creating shaded jar: null
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error creating shaded jar: null
	at org.apache.maven.plugins.shade.mojo.ShadeMojo.execute(ShadeMojo.java:540)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.apache.maven.plugins.shade.DefaultShader.addRemappedClass(DefaultShader.java:415)
	at org.apache.maven.plugins.shade.DefaultShader.shadeSingleJar(DefaultShader.java:219)
	at org.apache.maven.plugins.shade.DefaultShader.shadeJars(DefaultShader.java:179)
	at org.apache.maven.plugins.shade.DefaultShader.shade(DefaultShader.java:104)
	at org.apache.maven.plugins.shade.mojo.ShadeMojo.execute(ShadeMojo.java:454)
	... 22 more
```

**Comment by mdzhigarov** [comment]
That's odd... I am building it fine.
I am using Maven 3.3.9 with JDK build 1.8.0_151-b12

**Comment by chhsiao90** [comment]
okay, I will check myself why it failed!

**Comment by chhsiao90** [comment]
hi @mdzhigarov - There is a class `module-info.class` in the asm-6.0.jar that was compiled in jdk1.9, so the shaded plugin will failed to shade the asm jar.

You can download the jar at http://central.maven.org/maven2/org/ow2/asm/asm/6.0/ or find it in you local maven repository.

**Comment by mdzhigarov** [comment]
Still not clear... Why am I able to build the project fine then?

The shaded ASM seems to be of the correct 6.0 version, at least the .class sizes match the ones from the
http://central.maven.org/maven2/org/ow2/asm/asm/6.0/ jar

Are you saying that the latest maven shade plugin 3.1.0 does not work well with Jigsaw?

**Comment by chhsiao90** [comment]
Okay, you are using maven-shade-plugin:3.1.0 that was depends on asm-6.0_BETA that was able to read class compiled by Java 1.9.
I can package after I use maven-shade-plugin:3.10 to shade the classes.

Maybe you can explicit define the maven-shade-plugin version to prevent somebody are using old version of shade plugin and that will cause the shade failed.

**Comment by piotr0000** [comment]
Hello,
chhsiao90, could you merge this commit ? Maybe update these packages causes that modelmapper will work with Java 9. It will be very helpful.

**Pull request merged**
