### PR TITLE
feat!: new baseline of java 21

### PR DESCRIPTION
**Pull request by CynanX**
BREAKING CHANGE: Baseline moved to Java 21

### CODE REVIEW

**Comment by dlehammer** [comment]
Hi @CynanX ,

Consider bumping the other dependencies also, ex. Jackson is at 2.15.x currently, as this is a breaking change anyways 🤓

**Comment by CynanX** [comment]
Dependencies bumped.

**Comment by chhsiao90** [comment]
Thanks for this PR. We're not planning to drop the support for old JDKs. I fix it in #729 and will have a release soon.

**Comment by nexus061** [comment]
java 17 are not supported?

**Comment by CynanX** [comment]
> java 17 are not supported?

Not in this closed PR but the one that was merged it is.

**Pull request closed without merging**
