### PR TITLE
Fixes the OSGi headers generation. ASM, cglib, typetools & objen

### PR DESCRIPTION
**Pull request by mdzhigarov**
esis are now properly embedded into the bundle

### CODE REVIEW

**Comment by chhsiao90** [comment]
Thanks for this PR, can you disable the code formatter and re-push the commit?

**Comment by mdzhigarov** [comment]
Please note that I removed the shade plugin.
The required cglib classes are now shaded within the jar by the maven-bundle-plugin.
However, they are located and OSGi-exported within their original package name - net.sf.cglib.
In the past, they were wrapped and exported under the org.modelmapper.internal.cglib package.
While this could potentially be a breaking change for some people, I believe it is the right thing to do.
Prior to my commit, the OSGi headers were simply now working since the other shaded libs were not found by the modelmapper's own bundle classloader. 
So since this was never working in the first place, I think we can consider this a compatible change.

Btw, can you please do a quick release after this gets merged?

**Comment by chhsiao90** [comment]
Hi @mdzhigarov -
Thanks for the re-format and explanation.

There is some risk to shade the classes into the jar without changing their package.
If some people who use ModelMapper but also had cglib with different version in their dependency, then there will be class loading issue or maybe we can call it a dependency conflict.

Is there any reason that we need to keep the original package name?

**Comment by mdzhigarov** [comment]
> There is some risk to shade the classes into the jar without changing their package.
> If some people who use ModelMapper but also had cglib with different version in their dependency, then there will be class loading issue or maybe we can call it a dependency conflict.

OK, agreed...
I was so absorbed by the OSGi use case that I did not even think about the regular non-OSGi one :)

The reason why I moved these cglib classes is because I simply wanted to get rid of the jar, shade and replace plugins because I did not see any added value in them.
Now I see it - as the bundle plugin does not have the option to shade the classes under a different package.
So I guess the only way is to stick with all plugins.

I will refactor my commit to account for this limitation

**Comment by chhsiao90** [comment]
Ref #284

**Comment by mdzhigarov** [comment]
I have put some thoughts about this issue. Now I realize that not only we have a problem with the OSGi use case, but with the non-OSGi one as well.

The thing is that we need to have a self-contained artifact for both the OSGi and non-OSGi use cases.
That implies embedding asm, cglib, typetools and objenesis.
However, for the non-OSGi use case apparently we need to wrap the libs in the renamed org.modemapper.internal package so that we avoid any conflicts with the same libs with different version on the classpath.
However, if we relocate the asm, objenesis and typetools classes to a different package, the modelmapper jar itself is no longer able to load these classes since modelmapper's own java classes import classes from these libs with their original package name.
Which simply means that even though we have shaded the libs into the modelmapper jar, we still need to have the original libs on our classpath in order for things to work.
So the way shading is implemented today does not bring us any added value.

Same is valid for the OSGi use case. If we shade the libs under a different package name, the modulemapper's own bundle classloader is no longer able to load classes from the libs.

So if we want to have a self contained jar, our only option is to wrap the libs under their original name.
That is OK but as you already mentioned in your previous comment, embedding the libs in their original name would produce errors in the non-OSGi scenario because the user might have the libs already on his classpath, but in a different version.
Which is exactly why we have OSGi in the first place - to deal with this kinds of problems :)

So we have to accept that the way the modulemapper self-contained jar exist today - is broken.
Now we have to decide how to fix it in a way that satisfied both OSGi and non-OSGi use cases.

The only suitable option that I see right now is to produce 2 separate jars:
- one self contained modulemapper jar for the OSGi use case which embeds the libs.
- one jar for the non OSGi use case which:
    1) ... is either not self-contained, meaning that it would not embed the libs but rely that the user have them on his classpath.
    2) ... is self-contained, but with the risk to break client's code since the client might already have these libs on his classpath, but in a different version

If we choose option 2), we would actually not need two separate jars for OSGi and non-OSGi because the jars would basically be the same. So we can merge them into one.

Does this make sense? Please give me your feedback and I will implement the fix. 
If you feel like something that I wrote is not correct or if I simply did not explain it good enough, please tell me and I will try to explain it a bit better :)

**Comment by chhsiao90** [comment]
Provides two jar looks like a reasonable option to me.
From my perspective, my two jars will be looks like this
- all-in-one jar (as-is)
- dependency-exposed jar (It means that all dependency classes will not be included in the modelmapper.jar)

I guessed the dependency-exposed jar is ok work for OSGi, is it?

**Comment by mdzhigarov** [comment]
I just pushed my branch.
The modulemapper/core is now split into 2: modulemapper & modulemapper-all.
The modulemapper artifact is just plain modulemapper with all necessary OSGi import packages. 
The user is expected to then:
- Supply the necessary bundles that export these packages in his OSGi container.
- Supply the necessary jars on the application classpath in case he is not running withing the context of an OSGi container

The modulemapper-all artifact embeds modulemapper itself + all of its dependencies within itself.
The OSGi headers are adjusted.

Please build the project and comment whether this works for you or not

**Comment by chhsiao90** [comment]
Please rename modulemapper to modelmapper, thanks!

**Comment by chhsiao90** [comment]
Thanks, I will try to package the jars and give you feedback once I'm done!

**Comment by chhsiao90** [comment]
I suggest maybe we can move the all module to the root folder.
And maybe we can rename the all to osgi, and create another module all that contains the dependency classes as current modelmapper as is.
WDYT

```
.
├── all
├── osgi
├── core
├── examples
├── extensions
└── groovy

```

**Comment by mdzhigarov** [comment]
I am OK with moving the current "All" module to the root folder and renaming it to OSGi.

But the "All" module that you propose to contain all modelmapper classes as they are would be a problem.
2 reasons for that:
- As I already explained, the modelmapper as it currently is - has a broken classpath.
It simply doesn't work. If you don't believe me, you can try running it in a standalone mode, without having cglib, asm, objenesis and typetools on your classpath.

Like literally, try running vanilla modelmapper:
java -cp modelmapper.jar Main.java or something like that, where Main.java is a simple executable that uses modelmapper.
You would see the NoClassDefFoundErrors :)

The reason for that is that the shaded classes from the dependency libs are shaded under a different package name, which is a problem for the application class loader.

So it is pointless to have the "All" module as it exists today. It simply doesn't work.

- The second reason is - from Maven perspective it is hard to achieve.
Since the "All" module would be in a separate folder, it should only contain a single "pom.xml" file. There won't be a /src folder there. This automatically means that we cannot bind the maven bundle plugin to the "process-classes" phase since we don't have any classes to process in the first place.
So we have to completely rewrite the plugins for this pom.
But as I already said - this is pointless since what we are aiming for is a broken configuration.

Does that make sense?

**Comment by chhsiao90** [comment]
> As I already explained, the modelmapper as it currently is - has a broken classpath.
It simply doesn't work. If you don't believe me, you can try running it in a standalone mode, without having cglib, asm, objenesis and typetools on your classpath.

I had just tried.
I create a Main class like below.
run following code and it works fine.
```
mvn package -DskipTests
cd core\target
java -cp modelmapper-1.1.2-SNAPSHOT.jar Main
```
Am I missing something?

```java
import org.modelmapper.ModelMapper;
import org.modelmapper.PropertyMap;

public class Main {
  public static void main(String[] args) {
    ModelMapper modelMapper = new ModelMapper();
    modelMapper.addMappings(new PropertyMap<Source, Destination>() {
      protected void configure() {
        map().setName(source.getUser());
      }
    });

    Destination destination = modelMapper.map(new Source("user"), Destination.class);
    System.out.println(destination);
    assert destination.getName().equals("user");
  }

  static class Source {
    private String user;

    public Source(String user) {
      this.user = user;
    }

    public String getUser() {
      return user;
    }

    public void setUser(String user) {
      this.user = user;
    }
  }

  static class Destination {
    private String name;

    public String getName() {
      return name;
    }

    public void setName(String name) {
      this.name = name;
    }
  }
}
```

> The second reason is - from Maven perspective it is hard to achieve.
Since the "All" module would be in a separate folder, it should only contain a single "pom.xml" file. There won't be a /src folder there. This automatically means that we cannot bind the maven bundle plugin to the "process-classes" phase since we don't have any classes to process in the first place.
So we have to completely rewrite the plugins for this pom.
But as I already said - this is pointless since what we are aiming for is a broken configuration.

I just try move the maven-shade-plugin to this `all` module and it works fine.

The all module is just what current modelmapper as is. It provides advantage that the modelmapper's user can have its own cglib, objenesis dependency.

**Comment by mdzhigarov** [comment]
Hello,

OK, I finally understand what is going on here.

Seems that I have unintentionally mislead everyone here.
I was totally wrong in my assumption that the OSGi headers were corrupted.

I automatically thought so because from a first look it seems that asm/objenesis/typetools are moved under a different package name, which could not have normally worked out of the box without any additional shananinags. 
I have not had any experience so far with the maven-shade-plugin but now I do realize that relocating packages actually includes bytecode manipulation of the code that is being compiled, e.g. the modelmapper's code.
So it turns out that relocating packages, in addition to simply moving them to another location, involves actually changing the bytecode of the ModelMapper classes that use them.
Clever... But shady :)

So now I finally understand your concerns about my changes and why you insist on keeping the shaded classes.

Please understand that I initially opened this github issue with the intend to fix a classloading issue that I was experiencing in my environment, that at the time I thought was a common problem caused by incorrect OSGi headers.

Now that I understand how the shade plugin works, I no longer see it that way. Maybe the problem that I was experiencing was a completely different one afterall. 
I will get to the bottom of this.
I will test again on Jan 2th. when I get back to the office and check out how the shading is handled by the bundle classloaders of the OSGi container.

Thank you for the patience and the assistence! Sorry for the confusion that I caused!
Have happy holidays and we will talk again on Jan 2th.

**Comment by mdzhigarov** [comment]
Hello,

First off I'd start with wishing you a Happy New Year and best of luck to all ModelMapper contributors and team members! :)

I have invested some more time and finally found an elegant solution that would hopefully work for everyone.

The problem here is that the current ModelMapper pom generates incorrect Import-Package headers, i.e it includes objenesis, asm and typetools in the list of imported packages. But these are actually shaded into the lib so they are not needed at all since ModelMapper distributes them in itself.

The solution that I chose is described in details here:
https://issues.apache.org/jira/browse/FELIX-1184

Today we have the following plugin execution order:
- maven-bundle-plugin generates the MANIFEST.MF during process-classes
- replacer plugin "fixes" the MANIFEST.MF during prepare-package
- maven-jar-plugin jars the classes together with the previously generated MANIFEST.MF
- maven-shade-plugin shades asm/typetools/cglib/objenesis into the jar

This is not optimal, since the maven bundle plugin is executed before the shade plugin so now BND cannot account for the shaded classes. Therefore, it incorrectly generates Import-Package declarations for classes that are part of the distribution now.

Instead, I propose the following order:
- maven-jar-plugin jars the classes during package phase
- maven-shade-plugin shades asm/typetools/cglib/objenesis during package phase
- maven-dependency-plugin unpacks the previously generated jar in the target directory
- maven-bundle-plugin generates new MANIFEST.MF, this time accounting for the shaded classes, during package phase
- maven-jar-plugin jars the classes together with the newly generated MANIFEST.MF during package phase.

**Comment by chhsiao90** [comment]
Happy new year!
This PR looks great to me, thanks for your great help.
Is this PR still WIP or done? I think I can merge this PR if it was done.

**Comment by mdzhigarov** [comment]
It is done.

Could you please also have a look at https://github.com/modelmapper/modelmapper/pull/294
and give me an ETA for a release?

**Comment by chhsiao90** [comment]
I had reviewed #294 and will have a release this weekend.

**Comment by chhsiao90** [comment]
Already merged by #294

**Pull request closed without merging**
