### PR TITLE
Feature/182

### PR DESCRIPTION
**Pull request by ehmkah**
example howto handle inheritance.

### CODE REVIEW

**Comment by chhsiao90** [comment]
Thanks a lot for the contribution, will take a look later!

**Comment by chhsiao90** [comment]
LGTM, It looks really good! But I would prefer you to change the 4-spaces indent to 2-spaces indent because the ModelMapper follow this coding convention. That will be great. Thanks !

**Comment by chhsiao90** [comment]
@ehmkah - I had merged your previous PR #246, can you help rebase and resolved the conflict? Thanks!

**Comment by ehmkah** [comment]
That was the first time I rebased a branch. It was a little bit difficult but now I hope it is OK. 

I also corrected intend to 2 space like you wanted.

**Comment by chhsiao90** [comment]
Merged! Thanks for the contribution.

**Pull request merged**
