### PR TITLE
Protobuf extension breaks if protobuf message variables contain under…

### PR DESCRIPTION
**Pull request by wangzw**

### CODE REVIEW

**Comment by chhsiao90** [comment]
Hi @wangzw , thanks for your pull request!

It looks like the pull request enhanced the protocol buffer module to support snake case.
Can we separate the `snake_case ->CamelCase` and `camelCase -> CamelCase` into different methods for readability?

Thanks!

**Comment by wangzw** [comment]
> Hi @wangzw , thanks for your pull request!
> 
> It looks like the pull request enhanced the protocol buffer module to support snake_case.
> Can we separate the `snake_case ->CamelCase` and `camelCase -> CamelCase` into different methods for readability?
> 
> Thanks!

Done

**Comment by wangzw** [comment]
@chhsiao90 Thanks for accepting the pull request.

Is there any plan for the next release?

**Comment by chhsiao90** [comment]
I will have a release this week!

**Comment by gmishra123** [comment]
waiting for this to be released!!
Thanks.

**Comment by chhsiao90** [comment]
Hi @gmishra123 and @wangzw - v2.3.4 just release, please take a look, thanks.

**Pull request merged**
