### PR TITLE
Added possibility to map using condition and converter together.

### PR DESCRIPTION
**Pull request by sergey-soloviov**
This pull request refers to Issue #463 .

### CODE REVIEW

**Comment by chhsiao90** [comment]
Thanks for your pull request!

I think we don't need to change the code in `PropertyMap`, we should focus on `ConfigurableMapExpression` used by `ExpressionMap`. And it's better to follow the design in `PropertyMap`, the `when`, `using`, `with` should always be called in same order.

**Comment by sergey-soloviov** [comment]
I've updated the code base based on your suggestions above.

**Comment by westontan** [comment]
@chhsiao90 When can you merge this branch? I really need this feature.

**Comment by westontan** [comment]
The instance of ReferenceMapExpression even can't be cast to ConfigurableMapExpression...

**Comment by chhsiao90** [comment]
I will review and merge it recently, plan to release it by the end of June. Sorry for the inconvenience.

**Comment by westontan** [comment]
I am grateful for your help.

**Comment by chhsiao90** [comment]
Thanks @sergey-soloviov, the pull request looks good to me and merged.
I will have a release this weekend.

**Comment by chhsiao90** [comment]
v2.3.5 already released.

**Pull request merged**
